### ISSUE TITLE
Install Chromatic github app

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-modules/storybook#710]
In order to get feedback about the build status in Chromatic of the automatically deployed examples, we need to install the [Chromatic App](https://github.com/apps/chromatic-com). 

@chakAs3 @danielroe @Atinux I don't have sufficient rights to install the chromatic app, but have requested it to be installed in the nuxt-modules org. Could you please activate it? Thanks!

**Comment by danielroe** [comment]
Done ✅

**Comment by tobiasdiez** [comment]
Thanks a lot!

Apparently, one also needs oauth integration in order to link github repo to the project. I hope I can configure it once the initial permission has been setup. Could you please do this at https://github.com/settings/connections/applications/495b5c3cb5ae140436a0 ?

**Comment by danielroe** [comment]
Approved again.

**Comment by tobiasdiez** [comment]
Thanks @danielroe. It is however still not working. I'm in contact with the Chromatic support to resolve the situation. Could you please confirm that the following apps are installed in the nuxt-modules org?

Chromatic OAuth app > [here](https://github.com/settings/connections/applications/495b5c3cb5ae140436a0).
    Chromatic.com app > [here](https://github.com/apps/chromatic-com).

For me the first link says that "Access request pending" in the nuxt-modules org.

I believe the problem comes from the fact that in Chromatic the project is under my private account, and I'm not officially part of the nuxt-modules org. Would it be possible to invite me there (not sure what permissions are needed). We can also talk about this via email: code@tobiasdiez.de
