### ISSUE TITLE
Storybook version mismatch

### ISSUE THREAD

**Issue by shilman** [nuxt-modules/storybook#907]
Currently, `@storybook-vue/nuxt` has a peer dep on `storybook@9.0.5`:

https://github.com/nuxt-modules/storybook/blob/main/packages/storybook-addon/package.json#L67

This is problematic because Storybook releases patches every week and we are currently on 9.0.12 as of this issue.

This means that the installation instructions of `npm create storybook@latest` will fail for any package manager that properly respects versions. I suggest using a version range like `storybook@^9.0.5` or similar to resolve this.

Secondly, I suggest bumping the version of of `@storybook-vue/nuxt` to 9 so that it's obvious that it's compatible with Storybook 9. This is a personal preference, so feel free to ignore this suggestion if it doesn't feel right.

**Comment by tobiasdiez** [comment]
@shilman thanks for raising this issue and thanks to @robigan for your PR.

The reason for the very strict peer dependency constraint was that we had a lot of problems in the v8 release cycle were even minor storybook releases were breaking things here in this addon. This is also not a big surprise since the setup here is quite unconventional and uses some internal functionality of storybook.

I'm not sure how to best work around this situation. My plan in https://github.com/nuxt-modules/storybook/pull/782 was to make storybook a transitive dependency, instead of peer dependency. But I didn't yet find the time to finish the design and see how it would work in practice.

**Comment by shilman** [comment]
@tobiasdiez thanks for getting back to me and of course for all your hard work maintaining this.

Storybook 8.x was a pretty disruptive release cycle since we completely overhauled our internal package structure. By consolidating everything to a single package, `storybook`, we hope that the issues you experienced will be eliminated in the future.

That said, I completely understand wanting to defend getting broke in minors. And as much as I hope that the 9.x release cycle is much smoother than 8.x, I can't guarantee it.

I think the proper solution is to get Nuxt into Storybook's CI. Then we will know before every Storybook release whether some of our changes will break the install experience for new users. For small breakages we can probably submit fixes directly to this repo. And for more structural things, we can work with you to figure out a fix.

If you think that's a good solution, I can help get that set up in the Storybook monorepo. It might require some changes to the framework package to do it properly, to make this framework "look like" the core frameworks.

In the meantime, I'd suggest accepting `~9.0.5`, which will accept patch releases. The likelihood of a patch breaking the framework is dramatically lower than a minor.

**Comment by robigan** [comment]
> [@shilman](https://github.com/shilman) thanks for raising this issue and thanks to [@robigan](https://github.com/robigan) for your PR.
> 
> The reason for the very strict peer dependency constraint was that we had a lot of problems in the v8 release cycle were even minor storybook releases were breaking things here in this addon. This is also not a big surprise since the setup here is quite unconventional and uses some internal functionality of storybook.
> 
> I'm not sure how to best work around this situation. My plan in [#782](https://github.com/nuxt-modules/storybook/pull/782) was to make storybook a transitive dependency, instead of peer dependency. But I didn't yet find the time to finish the design and see how it would work in practice.

Hi, I saw #782 but given that it was still a draft, I decided to proceed with the changes based on how #882 was implemented, and that was with a semver range of `^9.0.4`, and last night, I thought that was the best fit approach, hence my changes.

> [@tobiasdiez](https://github.com/tobiasdiez) thanks for getting back to me and of course for all your hard work maintaining this.
> 
> Storybook 8.x was a pretty disruptive release cycle since we completely overhauled our internal package structure. By consolidating everything to a single package, `storybook`, we hope that the issues you experienced will be eliminated in the future.
> 
> That said, I completely understand wanting to defend getting broke in minors. And as much as I hope that the 9.x release cycle is much smoother than 8.x, I can't guarantee it.
> 
> I think the proper solution is to get Nuxt into Storybook's CI. Then we will know before every Storybook release whether some of our changes will break the install experience for new users. For small breakages we can probably submit fixes directly to this repo. And for more structural things, we can work with you to figure out a fix.
> 
> If you think that's a good solution, I can help get that set up in the Storybook monorepo. It might require some changes to the framework package to do it properly, to make this framework "look like" the core frameworks.
> 
> In the meantime, I'd suggest accepting `~9.0.5`, which will accept patch releases. The likelihood of a patch breaking the framework is dramatically lower than a minor.

Having seen this, I do agree with @shilman that perhaps `~9.0.5` may be most prudent, but @tobiasdiez you let me know which you prefer and I'll implement the changes

**Comment by tobiasdiez** [comment]
> I think the proper solution is to get Nuxt into Storybook's CI.

The basic framework tests already exist for Nuxt in the upstream Storybook repo. We would gain more confidence though if https://github.com/nuxt-modules/storybook/tree/main/examples/showcase were tested as well.

> In the meantime, I'd suggest accepting ~9.0.5, which will accept patch releases. 

Sounds good to me, let's try it!

**Comment by shilman** [comment]
Thanks @tobiasdiez -- I didn't realize that we're already testing Nuxt in CI. Those test stories are great -- I'll see whether there's an easy way to get them into the monorepo CI.

> Sounds good to me, let's try it!

🎉 🎉 🎉

**Comment by robigan** [comment]
> > I think the proper solution is to get Nuxt into Storybook's CI.
> 
> The basic framework tests already exist for Nuxt in the upstream Storybook repo. We would gain more confidence though if https://github.com/nuxt-modules/storybook/tree/main/examples/showcase were tested as well.
> 
> > In the meantime, I'd suggest accepting ~9.0.5, which will accept patch releases.
> 
> Sounds good to me, let's try it!

I'll make the change, sorry I've been on holiday with my GF

**Comment by robigan** [comment]
> > > I think the proper solution is to get Nuxt into Storybook's CI.
> > 
> > 
> > The basic framework tests already exist for Nuxt in the upstream Storybook repo. We would gain more confidence though if https://github.com/nuxt-modules/storybook/tree/main/examples/showcase were tested as well.
> > > In the meantime, I'd suggest accepting ~9.0.5, which will accept patch releases.
> > 
> > 
> > Sounds good to me, let's try it!
> 
> I'll make the change, sorry I've been on holiday with my GF

Done

**Comment by robigan** [comment]
cc @tobiasdiez

**Comment by robigan** [comment]
@tobiasdiez I just thought of this now, but what about updating the package version to follow the versions in upstream Storybook? I saw in another issue on here that apparently that's a recommended approach

**Comment by tobiasdiez** [comment]
Yes, it would be nice to align the major version number. There is currently a bug in the version update script, see https://github.com/nuxt-modules/storybook/pull/882#issuecomment-2987421451. It would be awesome, if you have the time to dive into this and fix it.

**Comment by davidyell** [comment]
This issue is still happening. I've invested 2 hours trying to get Storybook setup with Nuxt 3, and keep hitting the same issue. The Storybook cli tries to install using a constraint of `^9.0.5` which instead now, as mentioned in this thread, pulls down `9.0.18` (at time of writing) which then causes a version conflict in npm because the Nuxt module is locked to `9.0.5`.

Even trying to manually set the depedencies in my `package.json` to strictly `9.0.5` and then doing `npx storybook init` the cli command still causes a problem and I cannot figure out how to effect that install.

I am so keen to get Storybook working in our project to add test coverage for our Vue components, but currently it's not usable at all. Like honestly, just does not work.

If it's been fixed as this thread suggests, then a new release perhaps as `8.4.1` is broken for me

**Comment by tobiasdiez** [comment]
It's fixed in the nightly version of this module.

**Comment by davidyell** [comment]
~Great, where do I find the nightly? Trying to pull down the main branch seems to require `pnpm` which I don't have installed.~

Super, found the tag on NPM, thank you
